baseURL = 'https://micro-notes.pages.dev/'
title = 'Micro Notes'
theme = 'stack'
defaultContentLanguage = 'zh-cn'
hasCJKLanguage = true
timeZone = 'Asia/Shanghai'
paginate = 10

[languages]
  [languages."zh-cn"]
    label = "简体中文"
    weight = 1
    [[languages."zh-cn".menu.main]]
      identifier = "home"
      name = "首页"
      url = "/"
      weight = 1
    [[languages."zh-cn".menu.main]]
      identifier = "archives"
      name = "归档"
      url = "/archives/"
      weight = 2
    [[languages."zh-cn".menu.main]]
      identifier = "categories"
      name = "分类"
      url = "/categories/"
      weight = 3
    [[languages."zh-cn".menu.main]]
      identifier = "tags"
      name = "标签"
      url = "/tags/"
      weight = 4
    [[languages."zh-cn".menu.main]]
      identifier = "about"
      name = "关于"
      url = "/about/"
      weight = 5

[params]
  mainSections = ["posts"]
  [params.sidebar]
    subtitle = "记录技术点滴"
    [params.sidebar.links]
      github = "https://github.com/TechKitPro"
  [params.footer]
    since = 2026

[taxonomies]
  category = "categories"
  tag = "tags"
